version: '3.8'

services:
  whisper-server:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "7001:7001"
    runtime: nvidia
    environment:
      - NVIDIA_VISIBLE_DEVICES=all
      - NVIDIA_DRIVER_CAPABILITIES=compute,utility
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: 1
              capabilities: [gpu, utility, compute]